#开启sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上下文路径
server:
  servlet:
    context-path: /store
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  config-location: classpath:mapper/*.xml

user:
  address:
    max-count: 20

